FROM projectmonai/monai:1.0.0


RUN pip install pylint sh rope nibabel tensorboard scikit-image>=0.14.2 coverage parameterized pytorch-lightning segmentation-models-pytorch openpyxl

RUN pip install matplotlib seaborn h5py Pillow plotly protobuf joblib jupyterlab notebook voila ipywidgets spython tables xlrd==1.2.0

RUN pip install service_streamer